pipeline{

  agent{
    docker{
      image 'python: 2.7.16-slim'
    }
  }


  stages{
    stage('build'){
      when{
        changeset "**/vote/**"
      }
      steps{
        echo "compiling vote app"
        dir('vote'){
          sh 'pip install -i requirements.txt'
        }
      }
    }

    stage('test'){
      when{
        changeset "**/vote/**"
      }
      steps{
        echo 'running unit tests on result app'
        dir('vote'){
          sh 'nosetests -v'
        }
      }
    }
  }

  post{
    always{
      echo 'pipeline for vote complete'
    }
  }
}
