pipeline{
  agent none

  stages{
    stage('build'){
      agent{
        docker{
          image 'python:2.7.16-slim'
          args '--user root'
        }
      }
      when{
        changeset "**/vote/**"
      }
      steps{
        echo "compiling vote app"
        dir('vote'){
          sh 'pip install -r requirements.txt'
        }
      }
    }

    stage('test'){
      agent{
        docker{
          image 'python:2.7.16-slim'
          args '--user root'
        }
      }
      when{
        changeset "**/vote/**"
      }
      steps{
        echo 'running unit tests on vote app'
        dir('vote'){
          sh 'pip install -r requirements.txt'
          sh 'nosetests -v'
        }
      }
    }
    stage('vote integration'){
      agent any
      when{
        changeset "**/vote/**"
        branch 'master'
      }
      steps{
        echo 'running integration tests on vote app'
        dir('vote'){
          sh 'integration_test.sh'
        }
      }
    stage('docker-package') {
            agent any
            when{
                branch 'master'
                changeset "**/vote/**"
            }
            steps {
                echo 'Package vote app'
                script{
                      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                              def voteImage = docker.build("donquijotedelasnubes/vote:v${env.BUILD_ID}", "./vote")
                              voteImage.push()
                              voteImage.push("${env.BRANCH_NAME}")
                      }
                }
            }
    }
  }
  post{
      always{
        echo 'pipeline for vote complete'
      }
    }
}

