version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: donquijotedelasnubes/vote:master
    ports:
      - 5045:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - instavote


  result:
    image: donquijotedelasnubes/result:master
    ports:
      - 5046:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: donquijotedelasnubes/worker:master
    depends_on:
      - redis
      - db
    networks:
      - instavote
