pipeline {
    agent any

    tools{
      maven "maven 3.8.6"
    }
    stages {
        stage('Build') {
            when{
                changeset '**/wroker/**'
            }
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                  sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            when{
                changeset '**/wroker/**'
            }
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker'){
                  sh 'mvn clean test'
                }
            }
        }
        stage('Package') {
            when{
                branch 'master'
                changeset '**/wroker/**'
            }
            steps {
                echo 'Package worker app'
                dir('worker'){
                  sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        always{
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'Build pipeline run is completed.'
        }
    }
}



